project 'SwiftDemo.xcodeproj'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'

target 'SwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo
  pod 'SwpLocation', :path => '../'

end
