project 'SwpLocationDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SwpLocationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpLocationDemo
  inhibit_all_warnings!
  
  pod 'SwpLocation', :path => '../'
  
  pod 'Masonry'
  pod 'SwpCateGory/SwpColor'
  pod 'SwpCateGory/SwpSetButton'
  pod 'SwpCateGory/SwpAttributed'
  pod 'SwpCateGory/SwpCreateImage'
  

end
